"""API routes for real-time monitoring dashboard.

Provides REST endpoints for dashboard data including job status,
metrics, transactions, and error information.
"""

import logging
from uuid import UUID
from typing import Optional, Dict, Any, List

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from backend.database import get_db
from backend.monitoring import MetricsCollector, RealtimeEventBroadcaster

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/dashboard", tags=["dashboard"])


@router.get("/overview")
def get_dashboard_overview(
    org_id: UUID,
    db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """
    Get dashboard overview for an organization.

    Returns current status snapshot including:
    - Connection statistics
    - Recent metrics summary
    - Current jobs in progress
    - Recent errors

    Args:
        org_id: Organization UUID
        db: Database session

    Returns:
        Dashboard overview with current status and statistics
    """
    try:
        collector = MetricsCollector(db)

        # Get aggregate metrics for last hour
        agg_metrics = collector.calculate_aggregate_metrics(
            org_id, timeframe_minutes=60
        )

        # Get connection stats
        conn_stats = RealtimeEventBroadcaster.get_connection_stats()

        return {
            "status": "ok",
            "organization_id": str(org_id),
            "timestamp": None,  # Will be auto-generated by response
            "metrics": agg_metrics,
            "connections": {
                "total": conn_stats["total_connections"],
                "organization": conn_stats["organization_breakdown"].get(str(org_id), 0),
            },
            "dashboard_ready": True,
        }

    except Exception as e:
        logger.error(f"Failed to get dashboard overview: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/metrics/{timeframe}")
def get_metrics(
    org_id: UUID,
    timeframe: str,
    db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """
    Get aggregated metrics for an organization.

    Supports multiple timeframes:
    - 1h: Last hour
    - 6h: Last 6 hours
    - 24h: Last 24 hours
    - 7d: Last 7 days
    - 30d: Last 30 days

    Args:
        org_id: Organization UUID
        timeframe: Timeframe for metrics
        db: Database session

    Returns:
        Aggregated metrics for the timeframe
    """
    try:
        # Map timeframe to minutes
        timeframe_map = {
            "1h": 60,
            "6h": 360,
            "24h": 1440,
            "7d": 10080,
            "30d": 43200,
        }

        if timeframe not in timeframe_map:
            raise HTTPException(
                status_code=400,
                detail=f"Invalid timeframe. Supported: {', '.join(timeframe_map.keys())}"
            )

        minutes = timeframe_map[timeframe]
        collector = MetricsCollector(db)
        metrics = collector.calculate_aggregate_metrics(org_id, timeframe_minutes=minutes)

        return {
            "status": "ok",
            "organization_id": str(org_id),
            "timeframe": timeframe,
            "data": metrics,
        }

    except Exception as e:
        logger.error(f"Failed to get metrics: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/jobs")
def get_jobs(
    org_id: UUID,
    limit: int = Query(10, ge=1, le=100),
    db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """
    Get recent sync jobs for an organization.

    Args:
        org_id: Organization UUID
        limit: Number of jobs to return
        db: Database session

    Returns:
        List of recent sync jobs with current status
    """
    try:
        collector = MetricsCollector(db)

        # Get recent metrics (which represent sync jobs)
        metrics = collector.get_organization_metrics(org_id, timeframe_minutes=10080)

        # Limit results
        metrics = metrics[:limit]

        jobs = [
            {
                "job_id": str(m.job_id),
                "organization_id": str(m.organization_id),
                "timestamp": m.timestamp.isoformat(),
                "transactions_processed": m.transactions_processed,
                "transactions_failed": m.transactions_failed,
                "transactions_skipped": m.transactions_skipped,
                "duration_seconds": m.data.get("duration_seconds"),
                "status": m.data.get("sync_status"),
                "platform": m.data.get("platform"),
            }
            for m in metrics
        ]

        return {
            "status": "ok",
            "organization_id": str(org_id),
            "job_count": len(jobs),
            "jobs": jobs,
        }

    except Exception as e:
        logger.error(f"Failed to get jobs: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/jobs/{job_id}")
def get_job_details(
    org_id: UUID,
    job_id: UUID,
    db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """
    Get detailed metrics for a specific job.

    Args:
        org_id: Organization UUID
        job_id: Job UUID
        db: Database session

    Returns:
        Detailed metrics and statistics for the job
    """
    try:
        collector = MetricsCollector(db)
        metric = collector.get_job_metrics(job_id)

        if not metric or metric.organization_id != org_id:
            raise HTTPException(status_code=404, detail="Job not found")

        return {
            "status": "ok",
            "job_id": str(job_id),
            "organization_id": str(org_id),
            "data": metric.to_dict(),
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to get job details: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/transactions")
def get_transaction_counters(
    org_id: UUID,
    timeframe: str = Query("1h", description="Timeframe: 1h, 6h, 24h, 7d"),
    db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """
    Get transaction processing counters for an organization.

    Args:
        org_id: Organization UUID
        timeframe: Timeframe for metrics
        db: Database session

    Returns:
        Transaction processing statistics
    """
    try:
        # Map timeframe to minutes
        timeframe_map = {
            "1h": 60,
            "6h": 360,
            "24h": 1440,
            "7d": 10080,
        }

        if timeframe not in timeframe_map:
            raise HTTPException(status_code=400, detail="Invalid timeframe")

        minutes = timeframe_map[timeframe]
        collector = MetricsCollector(db)

        # Get metrics for timeframe
        metrics = collector.get_organization_metrics(org_id, timeframe_minutes=minutes)

        if not metrics:
            return {
                "status": "ok",
                "organization_id": str(org_id),
                "timeframe": timeframe,
                "transactions": {
                    "total_processed": 0,
                    "total_failed": 0,
                    "total_skipped": 0,
                    "success_rate": 0.0,
                },
            }

        # Sum up transactions across all jobs
        total_processed = sum(m.transactions_processed for m in metrics)
        total_failed = sum(m.transactions_failed for m in metrics)
        total_skipped = sum(m.transactions_skipped for m in metrics)

        success_rate = (
            ((total_processed - total_failed) / total_processed * 100)
            if total_processed > 0
            else 0.0
        )

        return {
            "status": "ok",
            "organization_id": str(org_id),
            "timeframe": timeframe,
            "transactions": {
                "total_processed": total_processed,
                "total_failed": total_failed,
                "total_skipped": total_skipped,
                "success_rate": round(success_rate, 2),
            },
        }

    except Exception as e:
        logger.error(f"Failed to get transaction counters: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/errors")
def get_errors(
    org_id: UUID,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """
    Get recent errors for an organization.

    Args:
        org_id: Organization UUID
        limit: Number of errors to return
        db: Database session

    Returns:
        List of recent errors with details
    """
    try:
        from backend.monitoring.models import ErrorLog
        from sqlalchemy import desc

        # Query recent errors
        errors = (
            db.query(ErrorLog)
            .filter(ErrorLog.organization_id == org_id)
            .order_by(desc(ErrorLog.created_at))
            .limit(limit)
            .all()
        )

        error_list = [
            {
                "error_id": str(e.id),
                "job_id": str(e.job_id),
                "error_type": e.error_type,
                "severity": e.severity.value,
                "message": e.error_message,
                "created_at": e.created_at.isoformat(),
                "is_resolved": e.is_resolved == "Y",
                "retry_count": e.retry_count,
            }
            for e in errors
        ]

        return {
            "status": "ok",
            "organization_id": str(org_id),
            "error_count": len(error_list),
            "errors": error_list,
        }

    except Exception as e:
        logger.error(f"Failed to get errors: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/health")
def dashboard_health(
    org_id: UUID,
    db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """
    Check dashboard health and connectivity.

    Args:
        org_id: Organization UUID
        db: Database session

    Returns:
        Health status of dashboard components
    """
    try:
        conn_stats = RealtimeEventBroadcaster.get_connection_stats()
        collector = MetricsCollector(db)

        # Try to get recent metrics
        metrics = collector.get_organization_metrics(org_id, timeframe_minutes=60)
        has_recent_data = len(metrics) > 0

        return {
            "status": "healthy",
            "organization_id": str(org_id),
            "components": {
                "websocket": "connected" if conn_stats["total_connections"] > 0 else "idle",
                "database": "connected",
                "metrics": "active" if has_recent_data else "idle",
            },
            "websocket_connections": conn_stats["total_connections"],
            "has_recent_data": has_recent_data,
        }

    except Exception as e:
        logger.error(f"Dashboard health check failed: {e}")
        return {
            "status": "unhealthy",
            "organization_id": str(org_id),
            "error": str(e),
        }
