"""initial_schema

Revision ID: 11da10f67c9e
Revises: 
Create Date: 2025-11-23 22:29:43.442804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11da10f67c9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)

    op.create_table('accounting_platforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('platform_version', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.String(length=500), nullable=False),
    sa.Column('client_secret_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('realm_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounting_platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_platforms_connection_status'), ['connection_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_platforms_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_platforms_last_sync_at'), ['last_sync_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_platforms_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_platforms_platform_name'), ['platform_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_platforms_realm_id'), ['realm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_platforms_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.String(length=500), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_name'), ['name'], unique=False)
        batch_op.create_index('ix_accounts_org_code', ['organization_id', 'code'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_platform_name'), ['platform_name'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=500), nullable=False),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_table_name'), ['table_name'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.String(length=500), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('contact_type', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_last_synced_at'), ['last_synced_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_platform_name'), ['platform_name'], unique=False)
        batch_op.create_index('ix_clients_platform_reference', ['platform_name', 'platform_id'], unique=True)

    op.create_table('ai_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('suggested_account_id', sa.UUID(), nullable=True),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_type', sa.String(length=50), nullable=True),
    sa.Column('target_entity_id', sa.UUID(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('response_tokens', sa.Integer(), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('suggested_category', sa.String(length=100), nullable=True),
    sa.Column('suggested_account_id_local', sa.UUID(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('was_used', sa.Boolean(), nullable=False),
    sa.Column('estimated_cost_gbp', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_account_id_local'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analysis_results_analysis_type'), ['analysis_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_results_is_approved'), ['is_approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_results_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analysis_results_target_entity_id'), ['target_entity_id'], unique=False)

    op.create_table('oauth_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['accounting_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_tokens_is_revoked'), ['is_revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_tokens_issued_at'), ['issued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_tokens_platform_id'), ['platform_id'], unique=False)

    op.create_table('sync_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['accounting_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_history_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_sync_status'), ['sync_status'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('platform_id', sa.String(length=500), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_is_reconciled'), ['is_reconciled'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_last_synced_at'), ['last_synced_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_platform_name'), ['platform_name'], unique=False)
        batch_op.create_index('ix_transactions_platform_ref', ['platform_name', 'platform_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index('ix_transactions_platform_ref')
        batch_op.drop_index(batch_op.f('ix_transactions_platform_name'))
        batch_op.drop_index(batch_op.f('ix_transactions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_last_synced_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_is_reconciled'))
        batch_op.drop_index(batch_op.f('ix_transactions_client_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_history_sync_status'))
        batch_op.drop_index(batch_op.f('ix_sync_history_started_at'))
        batch_op.drop_index(batch_op.f('ix_sync_history_platform_id'))
        batch_op.drop_index(batch_op.f('ix_sync_history_organization_id'))

    op.drop_table('sync_history')
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_platform_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_issued_at'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_is_revoked'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_expires_at'))

    op.drop_table('oauth_tokens')
    with op.batch_alter_table('ai_analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analysis_results_target_entity_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_results_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_results_is_approved'))
        batch_op.drop_index(batch_op.f('ix_ai_analysis_results_analysis_type'))

    op.drop_table('ai_analysis_results')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('ix_clients_platform_reference')
        batch_op.drop_index(batch_op.f('ix_clients_platform_name'))
        batch_op.drop_index(batch_op.f('ix_clients_organization_id'))
        batch_op.drop_index(batch_op.f('ix_clients_name'))
        batch_op.drop_index(batch_op.f('ix_clients_last_synced_at'))
        batch_op.drop_index(batch_op.f('ix_clients_is_active'))
        batch_op.drop_index(batch_op.f('ix_clients_email'))

    op.drop_table('clients')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_log_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_platform_name'))
        batch_op.drop_index(batch_op.f('ix_accounts_organization_id'))
        batch_op.drop_index('ix_accounts_org_code')
        batch_op.drop_index(batch_op.f('ix_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_type'))

    op.drop_table('accounts')
    with op.batch_alter_table('accounting_platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_platforms_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_accounting_platforms_realm_id'))
        batch_op.drop_index(batch_op.f('ix_accounting_platforms_platform_name'))
        batch_op.drop_index(batch_op.f('ix_accounting_platforms_organization_id'))
        batch_op.drop_index(batch_op.f('ix_accounting_platforms_last_sync_at'))
        batch_op.drop_index(batch_op.f('ix_accounting_platforms_is_active'))
        batch_op.drop_index(batch_op.f('ix_accounting_platforms_connection_status'))

    op.drop_table('accounting_platforms')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_is_active'))
        batch_op.drop_index(batch_op.f('ix_organizations_email'))
        batch_op.drop_index(batch_op.f('ix_organizations_created_at'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
